version: "3"

tasks:
  _prepare:
    deps:
      - gen
    silent: true

  dev:html:
    cmds:
      - |
        go tool templ generate --watch \
          --open-browser=false \
          --proxy="http://localhost:8080" --proxyport=3000 \
          --cmd="go run ./cmd/cli/ testhtml"
    silent: true

  run:
    deps:
      - _prepare
    cmds:
      - go run ./cmd/cli/ {{.CLI_ARGS}}
    silent: true

  test:
    deps:
      - _prepare
    cmds:
      - go test ./...
    silent: true

  sample1:
    deps:
      - _prepare
    cmds:
      - go run ./cmd/cli/ samples/nowindandroid-compile.txt prodReleaseCompileClasspath
    silent: true

  tidy:
    cmds:
      - go mod tidy
    silent: true

  gen:
    cmds:
      - mkdir -p internal/globals/gen
      - go tool templ generate
      - go generate ./...
    silent: true

  build:
    deps:
      - gen
    env:
      CGO_ENABLED: 0
    cmds:
      - go build -o out/lampa ./cmd/cli/
    silent: true

  build:all:
    deps:
      - gen
    env:
      CGO_ENABLED: 0
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o out/release/lampa-linux-amd64 ./cmd/cli
      - GOOS=linux GOARCH=arm64 go build -o out/release/lampa-linux-arm64 ./cmd/cli
      - GOOS=darwin GOARCH=amd64 go build -o out/release/lampa-darwin-amd64 ./cmd/cli
      - GOOS=darwin GOARCH=arm64 go build -o out/release/lampa-darwin-arm64 ./cmd/cli
      - GOOS=windows GOARCH=amd64 go build -o out/release/lampa-windows-amd64.exe ./cmd/cli
      - GOOS=windows GOARCH=arm64 go build -o out/release/lampa-windows-arm64.exe ./cmd/cli
