version: "3"

tasks:
  _prepare:
    deps:
      - gen
    silent: true

  dev:html:
    env:
      DEV: 1
    cmds:
      - |
        go tool templ generate --watch \
          --open-browser=false \
          --proxy="http://localhost:8080" --proxyport=3000 \
          --cmd="go run ./cmd/cli/ testhtml"
    silent: true

  run:
    deps:
      - _prepare
    cmds:
      - go run ./cmd/cli/ {{.CLI_ARGS}}
    silent: true

  test:
    deps:
      - _prepare
    cmds:
      - go test ./...
    silent: true

  tidy:
    cmds:
      - go mod tidy
    silent: true

  gen:
    deps:
      - gen:templ
    cmds:
      - mkdir -p internal/globals/gen
      - go generate ./...
    silent: true

  gen:templ:
    cmds:
      - go tool templ generate
      - cd server/core && go tool templ generate
    silent: true

  proto:gen:
    cmds:
      - |
        protoc --go_out=. \
          --go_opt=paths=source_relative \
          ./pkg/bundles/model/*.proto
    silent: true

  build:
    deps:
      - gen
    env:
      CGO_ENABLED: 0
    cmds:
      - go build -o out/lampa ./cmd/cli/
    silent: true

  version:
    cmds:
      - task run -- version
    silent: true

  build:all:
    deps:
      - gen
    env:
      CGO_ENABLED: 0
    cmds:
      - rm -r ./out/release || true
      - SUFFIX=$(date +%s%3N | shasum | head -c 8)
      - go build -o /tmp/lampa-$SUFFIX ./cmd/cli/
      - |
        VERSION=$(/tmp/lampa-$SUFFIX version --short)
        rm /tmp/lampa-$SUFFIX
        GOOS=linux GOARCH=amd64 go build -o out/release/lampa-$VERSION-linux-amd64 ./cmd/cli
        GOOS=linux GOARCH=arm64 go build -o out/release/lampa-$VERSION-linux-arm64 ./cmd/cli
        GOOS=darwin GOARCH=amd64 go build -o out/release/lampa-$VERSION-darwin-amd64 ./cmd/cli
        GOOS=darwin GOARCH=arm64 go build -o out/release/lampa-$VERSION-darwin-arm64 ./cmd/cli
        GOOS=windows GOARCH=amd64 go build -o out/release/lampa-$VERSION-windows-amd64.exe ./cmd/cli
        GOOS=windows GOARCH=arm64 go build -o out/release/lampa-$VERSION-windows-arm64.exe ./cmd/cli
      - sha256sum ./out/release/lampa-* > ./out/release/checksums.txt
