version: "3"

tasks:
  run:
    cmds:
      - go run cmd/cli/main.go {{.CLI_ARGS}}
    silent: true

  test:
    cmds:
      - go test ./...
    silent: true

  sample1:
    cmds:
      - go run cmd/cli/main.go samples/nowindandroid-compile.txt prodReleaseCompileClasspath
    silent: true
