version: "3"

tasks:
  test:
    cmds:
      - go test ./...
    silent: true

  sample1:
    cmds:
      - go run cmd/cli/main.go samples/nowindandroid-compile.txt prodReleaseCompileClasspath
    silent: true
