# typed: false
# frozen_string_literal: true

# This file was generated by Gemini.
# To update this file, please run the following command:
#
#   brew update-lampa-formula
#
class Lampa < Formula
  desc "Lampa"
  homepage "https://github.com/dector/lampa"
  version "0.1.0-5.dev"
  license "MIT"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dector/lampa/releases/download/v#{version}/lampa-darwin-amd64-#{version}"
    sha256 "7ee1f9bb9930a3a9a59496cfca8482473e7bc53b1c5093e99d4db71da0fe2ae2"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dector/lampa/releases/download/v#{version}/lampa-darwin-arm64-#{version}"
    sha256 "6b9969c0163a454d15f29ac5d96575bcac06df795044a90d4abbeb079c425b91"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dector/lampa/releases/download/v#{version}/lampa-linux-amd64-#{version}"
    sha256 "6fe45dc00a42a73c88ffc93d1af8bae749bc2c00076ff066528ec657da11fb13"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/dector/lampa/releases/download/v#{version}/lampa-linux-arm64-#{version}"
    sha256 "0bccc3c85bcd799b7e9f6d5f5d14a088ec719987e0fd5a49a0d07f774ebbf0d8"
  end

  def install
    bin.install "lampa-linux-amd64-#{version}" => "lampa" if OS.linux? && Hardware::CPU.intel?
    bin.install "lampa-linux-arm64-#{version}" => "lampa" if OS.linux? && Hardware::CPU.arm?
    bin.install "lampa-darwin-amd64-#{version}" => "lampa" if OS.mac? && Hardware::CPU.intel?
    bin.install "lampa-darwin-arm64-#{version}" => "lampa" if OS.mac? && Hardware::CPU.arm?
  end

  test do
    system "#{bin}/lampa", "version"
  end
end
