name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up Task
        uses: arduino/setup-task@v2

      - name: Build all binaries
        run: task build:all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            out/release/lampa-linux-amd64
            out/release/lampa-linux-arm64
            out/release/lampa-darwin-amd64
            out/release/lampa-darwin-arm64
            out/release/lampa-windows-amd64.exe
            out/release/lampa-windows-arm64.exe
