name: Run Renovate

on:
  schedule:
    - cron: "0 7 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Renovate
        uses: renovatebot/github-action@v43.0.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
