name: Snapshot build

on:
  push:
    branches:
      - trunk

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  snapshot:
    name: Create Snapshot
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: out/release

      - name: Update binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: snapshot
          prerelease: true
          files: |
            out/release/lampa-linux-amd64
            out/release/lampa-linux-arm64
            out/release/lampa-darwin-amd64
            out/release/lampa-darwin-arm64
            out/release/lampa-windows-amd64.exe
            out/release/lampa-windows-arm64.exe
